import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

//------------------------------------------------------------------------------

export const metadata: Metadata = {
  title: "Your Getaways Tour !",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AppRouterCacheProvider>
          <Toaster position="top-center" />
          {children}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
